-- ************************************** "BOOK"

CREATE TABLE "BOOK"
(
 BOOK_ID           bigint NOT NULL,
 BOOK_NAME         varchar NOT NULL,
 BOOK_PUBLISH_DATE int NOT NULL,
 CONSTRAINT PK_5 PRIMARY KEY ( BOOK_ID )
);

-- ************************************** "AUTHORS_BASE"

CREATE TABLE "AUTHOR"
(
 AUTHOR_ID          bigint NOT NULL,
 AUTHOR_NAME        varchar NOT NULL,
 AUTHOR_SURNAME     varchar NOT NULL,
 AUTHOR_SECOND_NAME varchar NULL,
 AUTHOR_BIRTH_DATE  int NOT NULL,
 CONSTRAINT PK_28 PRIMARY KEY ( AUTHOR_ID )
);

-- ************************************** "BOOK_AUTHORS"

CREATE TABLE "BOOK_AUTHOR"
(
 BOOK_ID   bigint NOT NULL,
 AUTHOR_ID bigint NOT NULL,
 CONSTRAINT PK_40 PRIMARY KEY ( BOOK_ID, AUTHOR_ID ),
 CONSTRAINT FK_34 FOREIGN KEY ( BOOK_ID ) REFERENCES "BOOK" ( BOOK_ID ),
 CONSTRAINT FK_37 FOREIGN KEY ( AUTHOR_ID ) REFERENCES "AUTHORS_BASE" ( AUTHOR_ID )
);

CREATE INDEX FK_36 ON "BOOK_AUTHOR"
(
 BOOK_ID
);

CREATE INDEX FK_39 ON "BOOK_AUTHOR"
(
 AUTHOR_ID
);

-- ************************************** "GENRES_BASE"

CREATE TABLE "GENRE"
(
 GENRE_ID   bigint NOT NULL,
 GENRE_NAME varchar NOT NULL,
 CONSTRAINT PK_10 PRIMARY KEY ( GENRE_ID )
);

-- ************************************** "BOOK_GENRES"

CREATE TABLE "BOOK_GENRE"
(
 BOOK_ID  bigint NOT NULL,
 GENRE_ID bigint NOT NULL,
 CONSTRAINT PK_14 PRIMARY KEY ( BOOK_ID, GENRE_ID ),
 CONSTRAINT FK_20 FOREIGN KEY ( BOOK_ID ) REFERENCES "BOOK" ( BOOK_ID ),
 CONSTRAINT FK_23 FOREIGN KEY ( GENRE_ID ) REFERENCES "GENRES_BASE" ( GENRE_ID )
);

CREATE INDEX FK_22 ON "BOOK_GENRE"
(
 BOOK_ID
);

CREATE INDEX FK_25 ON "BOOK_GENRE"
(
 GENRE_ID
);

-- ************************************** "USERS"

CREATE TABLE "USERS"
(
 USER_ID           bigint NOT NULL,
 USER_NAME         varchar NOT NULL,
 USER_SURNAME      varchar NOT NULL,
 USER_SECOND_NAME  varchar NULL,
 USER_PHONE_NUMBER bigint NOT NULL,
 CONSTRAINT PK_43 PRIMARY KEY ( USER_ID )
);

-- ************************************** "BOOK_ORDER"

CREATE TABLE "ORDER"
(
 ORDER_ID         bigint NOT NULL,
 USER_ID          bigint NOT NULL,
 BOOK_ID          bigint NOT NULL,
 ORDER_START_DATE date NOT NULL,
 ORDER_END_DATE   date NOT NULL,
 CONSTRAINT PK_50 PRIMARY KEY ( ORDER_ID ),
 CONSTRAINT FK_53 FOREIGN KEY ( USER_ID ) REFERENCES "USERS" ( USER_ID ),
 CONSTRAINT FK_56 FOREIGN KEY ( BOOK_ID ) REFERENCES "BOOK" ( BOOK_ID )
);

CREATE INDEX FK_55 ON "ORDER"
(
 USER_ID
);

CREATE INDEX FK_58 ON "ORDER"
(
 BOOK_ID
);
